package com.cni.stock.model;

// Generated 7 juil. 2014 18:37:58 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", catalog = "stock")
public class Facture implements java.io.Serializable {

	private int idFacture;
	private Fournisseur fournisseur;
	private String description;
	private Date jour;
	private String libJour;
	private Integer credit;
	private Integer reglement;
	private Integer reste;

	public Facture() {
	}

	public Facture(int idFacture) {
		this.idFacture = idFacture;
	}

	public Facture(int idFacture, Fournisseur fournisseur, String description,
			Date jour, String libJour, Integer credit, Integer reglement,
			Integer reste) {
		this.idFacture = idFacture;
		this.fournisseur = fournisseur;
		this.description = description;
		this.jour = jour;
		this.libJour = libJour;
		this.credit = credit;
		this.reglement = reglement;
		this.reste = reste;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_facture", unique = true, nullable = false)
	public int getIdFacture() {
		return this.idFacture;
	}

	public void setIdFacture(int idFacture) {
		this.idFacture = idFacture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_fournisseur")
	public Fournisseur getFournisseur() {
		return this.fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	@Column(name = "description", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "jour", length = 13)
	public Date getJour() {
		return this.jour;
	}

	public void setJour(Date jour) {
		this.jour = jour;
	}

	@Column(name = "lib_jour", length = 256)
	public String getLibJour() {
		return this.libJour;
	}

	public void setLibJour(String libJour) {
		this.libJour = libJour;
	}

	@Column(name = "credit")
	public Integer getCredit() {
		return this.credit;
	}

	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	@Column(name = "reglement")
	public Integer getReglement() {
		return this.reglement;
	}

	public void setReglement(Integer reglement) {
		this.reglement = reglement;
	}

	@Column(name = "reste")
	public Integer getReste() {
		return this.reste;
	}

	public void setReste(Integer reste) {
		this.reste = reste;
	}

}
