package com.cni.stock.model;

// Generated 7 juil. 2014 18:37:58 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", catalog = "stock")
public class Produit implements java.io.Serializable {

	private int idProduit;
	private Unite unite;
	private Categorie categorie;
	private String code;
	private String libelle;
	private Integer stock;
	private String description;
	private Integer ordre;
	private Integer prix;
	private Set<Vendre> vendres = new HashSet<Vendre>(0);
	private Set<LigneCommande> ligneCommandes = new HashSet<LigneCommande>(0);

	public Produit() {
	}

	public Produit(int idProduit) {
		this.idProduit = idProduit;
	}

	public Produit(int idProduit, Unite unite, Categorie categorie,
			String code, String libelle, Integer stock, String description,
			Integer ordre, Integer prix, Set<Vendre> vendres,
			Set<LigneCommande> ligneCommandes) {
		this.idProduit = idProduit;
		this.unite = unite;
		this.categorie = categorie;
		this.code = code;
		this.libelle = libelle;
		this.stock = stock;
		this.description = description;
		this.ordre = ordre;
		this.prix = prix;
		this.vendres = vendres;
		this.ligneCommandes = ligneCommandes;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_produit", unique = true, nullable = false)
	public int getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(int idProduit) {
		this.idProduit = idProduit;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_unite")
	public Unite getUnite() {
		return this.unite;
	}

	public void setUnite(Unite unite) {
		this.unite = unite;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_categorie")
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@Column(name = "code", length = 256)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle", length = 256)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "stock")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	@Column(name = "description", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ordre")
	public Integer getOrdre() {
		return this.ordre;
	}

	public void setOrdre(Integer ordre) {
		this.ordre = ordre;
	}

	@Column(name = "prix")
	public Integer getPrix() {
		return this.prix;
	}

	public void setPrix(Integer prix) {
		this.prix = prix;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<Vendre> getVendres() {
		return this.vendres;
	}

	public void setVendres(Set<Vendre> vendres) {
		this.vendres = vendres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<LigneCommande> getLigneCommandes() {
		return this.ligneCommandes;
	}

	public void setLigneCommandes(Set<LigneCommande> ligneCommandes) {
		this.ligneCommandes = ligneCommandes;
	}

}
