package com.cni.stock.model;

// Generated 7 juil. 2014 18:37:58 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * Unite generated by hbm2java
 */
@Entity
@Table(name = "unite", catalog = "stock")
public class Unite implements java.io.Serializable {

	private int idUnite;
	private String code;
	private String libelle;
	private String description;
	private Set<Produit> produits = new HashSet<Produit>(0);

	public Unite() {
	}

	public Unite(int idUnite) {
		this.idUnite = idUnite;
	}

	public Unite(int idUnite, String code, String libelle, String description,
			Set<Produit> produits) {
		this.idUnite = idUnite;
		this.code = code;
		this.libelle = libelle;
		this.description = description;
		this.produits = produits;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_unite", unique = true, nullable = false)
	public int getIdUnite() {
		return this.idUnite;
	}

	public void setIdUnite(int idUnite) {
		this.idUnite = idUnite;
	}

	@Column(name = "code", length = 256)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle", length = 256)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "description", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unite")
	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

}
