package com.cni.stock.model;

// Generated 7 juil. 2014 18:37:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * Vendre generated by hbm2java
 */
@Entity
@Table(name = "vendre", catalog = "stock")
public class Vendre implements java.io.Serializable {

	private int idVendre;
	private Fournisseur fournisseur;
	private Produit produit;
	private Integer prix;

	public Vendre() {
	}

	public Vendre(int idVendre, Fournisseur fournisseur, Produit produit) {
		this.idVendre = idVendre;
		this.fournisseur = fournisseur;
		this.produit = produit;
	}

	public Vendre(int idVendre, Fournisseur fournisseur, Produit produit,
			Integer prix) {
		this.idVendre = idVendre;
		this.fournisseur = fournisseur;
		this.produit = produit;
		this.prix = prix;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_vendre", unique = true, nullable = false)
	public int getIdVendre() {
		return this.idVendre;
	}

	public void setIdVendre(int idVendre) {
		this.idVendre = idVendre;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_fournisseur", nullable = false)
	public Fournisseur getFournisseur() {
		return this.fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_produit", nullable = false)
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Column(name = "prix")
	public Integer getPrix() {
		return this.prix;
	}

	public void setPrix(Integer prix) {
		this.prix = prix;
	}

}
