package com.cni.stock.model;

// Generated 7 juil. 2014 18:37:58 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "commande", catalog = "stock")
public class Commande implements java.io.Serializable {

	private int idCommande;
	private Fournisseur fournisseur;
	private String code;
	private String type;
	private Date jour;
	private String libJour;
	private String description;
	private Integer prixTotal;
	private Set<LigneCommande> ligneCommandes = new HashSet<LigneCommande>(0);

	public Commande() {
	}

	public Commande(int idCommande) {
		this.idCommande = idCommande;
	}

	public Commande(int idCommande, Fournisseur fournisseur, String code,
			String type, Date jour, String libJour, String description,
			Integer prixTotal, Set<LigneCommande> ligneCommandes) {
		this.idCommande = idCommande;
		this.fournisseur = fournisseur;
		this.code = code;
		this.type = type;
		this.jour = jour;
		this.libJour = libJour;
		this.description = description;
		this.prixTotal = prixTotal;
		this.ligneCommandes = ligneCommandes;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_commande", unique = true, nullable = false)
	public int getIdCommande() {
		return this.idCommande;
	}

	public void setIdCommande(int idCommande) {
		this.idCommande = idCommande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_fournisseur")
	public Fournisseur getFournisseur() {
		return this.fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	@Column(name = "code", length = 256)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "type", length = 256)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "jour", length = 13)
	public Date getJour() {
		return this.jour;
	}

	public void setJour(Date jour) {
		this.jour = jour;
	}

	@Column(name = "lib_jour", length = 256)
	public String getLibJour() {
		return this.libJour;
	}

	public void setLibJour(String libJour) {
		this.libJour = libJour;
	}

	@Column(name = "description", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "prix_total")
	public Integer getPrixTotal() {
		return this.prixTotal;
	}

	public void setPrixTotal(Integer prixTotal) {
		this.prixTotal = prixTotal;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "commande")
	public Set<LigneCommande> getLigneCommandes() {
		return this.ligneCommandes;
	}

	public void setLigneCommandes(Set<LigneCommande> ligneCommandes) {
		this.ligneCommandes = ligneCommandes;
	}

}
