package com.cni.stock.model;

// Generated 7 juil. 2014 18:37:58 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * Fournisseur generated by hbm2java
 */
@Entity
@Table(name = "fournisseur", catalog = "stock")
public class Fournisseur implements java.io.Serializable {

	private int idFournisseur;
	private String code;
	private String nom;
	private String prenom;
	private String adresse;
	private String description;
	private String telephone1;
	private String telephone2;
	private Integer credit;
	private Set<Vendre> vendres = new HashSet<Vendre>(0);
	private Set<Commande> commandes = new HashSet<Commande>(0);
	private Set<Facture> factures = new HashSet<Facture>(0);

	public Fournisseur() {
	}

	public Fournisseur(int idFournisseur) {
		this.idFournisseur = idFournisseur;
	}

	public Fournisseur(int idFournisseur, String code, String nom,
			String prenom, String adresse, String description,
			String telephone1, String telephone2, Integer credit,
			Set<Vendre> vendres, Set<Commande> commandes, Set<Facture> factures) {
		this.idFournisseur = idFournisseur;
		this.code = code;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.description = description;
		this.telephone1 = telephone1;
		this.telephone2 = telephone2;
		this.credit = credit;
		this.vendres = vendres;
		this.commandes = commandes;
		this.factures = factures;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_fournisseur", unique = true, nullable = false)
	public int getIdFournisseur() {
		return this.idFournisseur;
	}

	public void setIdFournisseur(int idFournisseur) {
		this.idFournisseur = idFournisseur;
	}

	@Column(name = "code", length = 256)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "nom", length = 256)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 256)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "adresse", length = 256)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "description", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "telephone1", length = 256)
	public String getTelephone1() {
		return this.telephone1;
	}

	public void setTelephone1(String telephone1) {
		this.telephone1 = telephone1;
	}

	@Column(name = "telephone2", length = 256)
	public String getTelephone2() {
		return this.telephone2;
	}

	public void setTelephone2(String telephone2) {
		this.telephone2 = telephone2;
	}

	@Column(name = "credit")
	public Integer getCredit() {
		return this.credit;
	}

	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fournisseur")
	public Set<Vendre> getVendres() {
		return this.vendres;
	}

	public void setVendres(Set<Vendre> vendres) {
		this.vendres = vendres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fournisseur")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fournisseur")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

}
