package com.cni.stock.model;

// Generated 7 juil. 2014 18:37:58 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * Invite generated by hbm2java
 */
@Entity
@Table(name = "invite", catalog = "stock")
public class Invite implements java.io.Serializable {

	private int idInvite;
	private Date jour;
	private String libJour;
	private Integer nombre;
	private String repat1;
	private String repat2;
	private String repat3;
	private Integer montant;

	public Invite() {
	}

	public Invite(int idInvite) {
		this.idInvite = idInvite;
	}

	public Invite(int idInvite, Date jour, String libJour, Integer nombre,
			String repat1, String repat2, String repat3, Integer montant) {
		this.idInvite = idInvite;
		this.jour = jour;
		this.libJour = libJour;
		this.nombre = nombre;
		this.repat1 = repat1;
		this.repat2 = repat2;
		this.repat3 = repat3;
		this.montant = montant;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_invite", unique = true, nullable = false)
	public int getIdInvite() {
		return this.idInvite;
	}

	public void setIdInvite(int idInvite) {
		this.idInvite = idInvite;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "jour", length = 13)
	public Date getJour() {
		return this.jour;
	}

	public void setJour(Date jour) {
		this.jour = jour;
	}

	@Column(name = "lib_jour", length = 256)
	public String getLibJour() {
		return this.libJour;
	}

	public void setLibJour(String libJour) {
		this.libJour = libJour;
	}

	@Column(name = "nombre")
	public Integer getNombre() {
		return this.nombre;
	}

	public void setNombre(Integer nombre) {
		this.nombre = nombre;
	}

	@Column(name = "repat1", length = 256)
	public String getRepat1() {
		return this.repat1;
	}

	public void setRepat1(String repat1) {
		this.repat1 = repat1;
	}

	@Column(name = "repat2", length = 256)
	public String getRepat2() {
		return this.repat2;
	}

	public void setRepat2(String repat2) {
		this.repat2 = repat2;
	}

	@Column(name = "repat3", length = 256)
	public String getRepat3() {
		return this.repat3;
	}

	public void setRepat3(String repat3) {
		this.repat3 = repat3;
	}

	@Column(name = "montant")
	public Integer getMontant() {
		return this.montant;
	}

	public void setMontant(Integer montant) {
		this.montant = montant;
	}

}
