package com.cni.stock.model;

// Generated 7 juil. 2014 18:37:58 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", catalog = "stock")
public class Type implements java.io.Serializable {

	private int idType;
	private String code;
	private String libelle;
	private String description;
	private Set<Categorie> categories = new HashSet<Categorie>(0);

	public Type() {
	}

	public Type(int idType) {
		this.idType = idType;
	}

	public Type(int idType, String code, String libelle, String description,
			Set<Categorie> categories) {
		this.idType = idType;
		this.code = code;
		this.libelle = libelle;
		this.description = description;
		this.categories = categories;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_type", unique = true, nullable = false)
	public int getIdType() {
		return this.idType;
	}

	public void setIdType(int idType) {
		this.idType = idType;
	}

	@Column(name = "code", length = 256)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle", length = 256)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "description", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<Categorie> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Categorie> categories) {
		this.categories = categories;
	}

}
